components_configurations_folder: ~/w/catkin_ws/src/localization_performance_modelling/config/component_configurations
gazebo_model_path_env_var: []
gazebo_plugin_path_env_var: [~/w/catkin_ws/build/gazebo_plugins/]

supervisor_component: localization_benchmark_supervisor

components_configuration:
  supervisor: localization_benchmark_supervisor/localization_benchmark_supervisor.yaml
  amcl: amcl/amcl.yaml
  slam_toolbox: slam_toolbox/slam_toolbox.yaml
  move_base: move_base/move_base_tb3.yaml
  rviz: rviz/default_view.rviz

combinatorial_parameters:
  localization_node: [slam_toolbox]
  beta: [[0.035, 0.035, 0.01, 0.01]]
  laser_scan_max_range: [3.5, 30.0]
  laser_scan_fov_deg: [90, 180, 270, 359]
  map_resolution: [0.05]
  map_source: [slam_toolbox_map]